name: Trigger auto deployment for container-app-5p2szhs4h2vzc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-5p2szhs4h2vzc-AutoDeployTrigger-fad8db5f-f13a-4956-8326-ed53c5e9a577.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrydgphzragcuz3s.azurecr.io
          username: ${{ secrets.CONTAINERAPP5P2SZHS4H2VZC_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP5P2SZHS4H2VZC_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrydgphzragcuz3s.azurecr.io/container-app-5p2szhs4h2vzc:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP5P2SZHS4H2VZC_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-5p2szhs4h2vzc -g githubactiontestappcontainer8a10 --server containerregistrydgphzragcuz3s.azurecr.io --username  ${{ secrets.CONTAINERAPP5P2SZHS4H2VZC_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP5P2SZHS4H2VZC_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-5p2szhs4h2vzc -g githubactiontestappcontainer8a10 --image containerregistrydgphzragcuz3s.azurecr.io/container-app-5p2szhs4h2vzc:${{ github.sha }}
